[[XSLT]]
arch = "i686"
git-tree-sha1 = "f64701ce0fd6c6696026161ed27407ec76e7000a"
libc = "musl"
os = "linux"

    [[XSLT.download]]
    sha256 = "8b934063440886ee056f98566e0dd109bdeed44928cfe92526c05b63c15e51c0"
    url = "https://github.com/JuliaBinaryWrappers/XSLT_jll.jl/releases/download/XSLT-v1.1.33+2/XSLT.v1.1.33.i686-linux-musl.tar.gz"
[[XSLT]]
arch = "aarch64"
git-tree-sha1 = "747b269382a77af808cf5685c3b16328f0338747"
libc = "musl"
os = "linux"

    [[XSLT.download]]
    sha256 = "bb0de9db85d88e3089d4fa24c04ecd792f804072576e0377c6bd5442a0fae7b0"
    url = "https://github.com/JuliaBinaryWrappers/XSLT_jll.jl/releases/download/XSLT-v1.1.33+2/XSLT.v1.1.33.aarch64-linux-musl.tar.gz"
[[XSLT]]
arch = "i686"
git-tree-sha1 = "b1871537c8ccc434ee2b5a4a731e5e91bcd64b20"
os = "windows"

    [[XSLT.download]]
    sha256 = "483b83b7a5d3286e92a5ab935b73939fc56a145b98d7a6e3caa257341afac528"
    url = "https://github.com/JuliaBinaryWrappers/XSLT_jll.jl/releases/download/XSLT-v1.1.33+2/XSLT.v1.1.33.i686-w64-mingw32.tar.gz"
[[XSLT]]
arch = "x86_64"
git-tree-sha1 = "b5c36c10e94328651822883e1750865f10b74e2c"
os = "windows"

    [[XSLT.download]]
    sha256 = "e29fa7cbc59596fc15ff80e40c7d3dbbe111f68bbc674795e42bea9bee548ed4"
    url = "https://github.com/JuliaBinaryWrappers/XSLT_jll.jl/releases/download/XSLT-v1.1.33+2/XSLT.v1.1.33.x86_64-w64-mingw32.tar.gz"
[[XSLT]]
arch = "armv7l"
git-tree-sha1 = "f0b488adc1b93e9a600b10910813cd293618eb74"
libc = "glibc"
os = "linux"

    [[XSLT.download]]
    sha256 = "19c7cb1df411c8253620252fd66b334e7a055e505f9c1c8b1356e464a13a08c5"
    url = "https://github.com/JuliaBinaryWrappers/XSLT_jll.jl/releases/download/XSLT-v1.1.33+2/XSLT.v1.1.33.armv7l-linux-gnueabihf.tar.gz"
[[XSLT]]
arch = "armv7l"
git-tree-sha1 = "1a2755aaff9cf98cade32bd2a854dfa726467a0c"
libc = "musl"
os = "linux"

    [[XSLT.download]]
    sha256 = "ec0a6e9d0b2189aade6603c7fcfe780359b26bd7c2a5748c0735a23ff8b5966c"
    url = "https://github.com/JuliaBinaryWrappers/XSLT_jll.jl/releases/download/XSLT-v1.1.33+2/XSLT.v1.1.33.armv7l-linux-musleabihf.tar.gz"
[[XSLT]]
arch = "i686"
git-tree-sha1 = "ba2811d86b97104a21be3a3bf4a54ff88512e8d3"
libc = "glibc"
os = "linux"

    [[XSLT.download]]
    sha256 = "d5cab9a57a12d77bbd4367a415a6bd8381f5a0927d07721c9f6a92132e0ad228"
    url = "https://github.com/JuliaBinaryWrappers/XSLT_jll.jl/releases/download/XSLT-v1.1.33+2/XSLT.v1.1.33.i686-linux-gnu.tar.gz"
[[XSLT]]
arch = "x86_64"
git-tree-sha1 = "3cd20f6135e742ca5c9828e2965ae5b858721ad0"
libc = "glibc"
os = "linux"

    [[XSLT.download]]
    sha256 = "2e61ea1608afe4cdf2a94f8b0fd3e7d0da89078465e490d68a1378b3f96aba22"
    url = "https://github.com/JuliaBinaryWrappers/XSLT_jll.jl/releases/download/XSLT-v1.1.33+2/XSLT.v1.1.33.x86_64-linux-gnu.tar.gz"
[[XSLT]]
arch = "powerpc64le"
git-tree-sha1 = "6198d5d7c06540d01ba28ca253c339adf80f71f2"
libc = "glibc"
os = "linux"

    [[XSLT.download]]
    sha256 = "1dc25249bd1faf2b30fac5328e3e214a83b3a172dd89d86d87b3cb443ee4133c"
    url = "https://github.com/JuliaBinaryWrappers/XSLT_jll.jl/releases/download/XSLT-v1.1.33+2/XSLT.v1.1.33.powerpc64le-linux-gnu.tar.gz"
[[XSLT]]
arch = "x86_64"
git-tree-sha1 = "dcf1baeefd8b5b28127aa927d41fabb94d3b20b1"
os = "macos"

    [[XSLT.download]]
    sha256 = "7ecefa7a948cefe6f491593d5b8d32f84c49657adcfd2e97636e9de88a358edf"
    url = "https://github.com/JuliaBinaryWrappers/XSLT_jll.jl/releases/download/XSLT-v1.1.33+2/XSLT.v1.1.33.x86_64-apple-darwin14.tar.gz"
[[XSLT]]
arch = "aarch64"
git-tree-sha1 = "500837bda6c00f83f412995a8f7c83ea54913def"
libc = "glibc"
os = "linux"

    [[XSLT.download]]
    sha256 = "a00b7bdf5c5bf92faefd26b64041b172f8c1cf713865278fab5afb2d8e628f03"
    url = "https://github.com/JuliaBinaryWrappers/XSLT_jll.jl/releases/download/XSLT-v1.1.33+2/XSLT.v1.1.33.aarch64-linux-gnu.tar.gz"
[[XSLT]]
arch = "x86_64"
git-tree-sha1 = "fadb42502f5e1537f85103a793e7c4ffc038e752"
os = "freebsd"

    [[XSLT.download]]
    sha256 = "ac661c690c582fe3c4725d313c3aadaf659ad88ff2140eaf491cb5707c390853"
    url = "https://github.com/JuliaBinaryWrappers/XSLT_jll.jl/releases/download/XSLT-v1.1.33+2/XSLT.v1.1.33.x86_64-unknown-freebsd11.1.tar.gz"
[[XSLT]]
arch = "x86_64"
git-tree-sha1 = "9a2af509e559117f091b68978b05b0915fa4ec24"
libc = "musl"
os = "linux"

    [[XSLT.download]]
    sha256 = "92b3925981ef0500f394395a7817f092a53eb6596c151e11169f91b4683738b4"
    url = "https://github.com/JuliaBinaryWrappers/XSLT_jll.jl/releases/download/XSLT-v1.1.33+2/XSLT.v1.1.33.x86_64-linux-musl.tar.gz"
