[[XSLT]]
arch = "i686"
git-tree-sha1 = "a070a789682c5686398fa50aa083adfdefa25c51"
libc = "musl"
os = "linux"

    [[XSLT.download]]
    sha256 = "283e7efc76771a6c00df9ecc737a545fe2d375688e99c2dfedc4047303054a9e"
    url = "https://github.com/JuliaBinaryWrappers/XSLT_jll.jl/releases/download/XSLT-v1.1.33+1/XSLT.v1.1.33.i686-linux-musl.tar.gz"
[[XSLT]]
arch = "aarch64"
git-tree-sha1 = "711204dc19612b3cc20f3a3ae8ddb961ed84f343"
libc = "musl"
os = "linux"

    [[XSLT.download]]
    sha256 = "3052d270d02661545c89a9fd2638ee22beb7ae75fd1193e42660178c6c9a3e79"
    url = "https://github.com/JuliaBinaryWrappers/XSLT_jll.jl/releases/download/XSLT-v1.1.33+1/XSLT.v1.1.33.aarch64-linux-musl.tar.gz"
[[XSLT]]
arch = "i686"
git-tree-sha1 = "d3790c3f3546b968246a92d7dd085cada5f61323"
os = "windows"

    [[XSLT.download]]
    sha256 = "fe54ad01d3c80bfa7b6a92ad67d9544fe638922fa62bfb0ed04ccd952482d2d2"
    url = "https://github.com/JuliaBinaryWrappers/XSLT_jll.jl/releases/download/XSLT-v1.1.33+1/XSLT.v1.1.33.i686-w64-mingw32.tar.gz"
[[XSLT]]
arch = "x86_64"
git-tree-sha1 = "e687f9c0ca1ec177dcaae4b1dc3da135c5f699ce"
os = "windows"

    [[XSLT.download]]
    sha256 = "bf1b73fdf16b791fa3bb08b5e923467fc1f1316ae254c06e6c8fad8cd7d3ccb7"
    url = "https://github.com/JuliaBinaryWrappers/XSLT_jll.jl/releases/download/XSLT-v1.1.33+1/XSLT.v1.1.33.x86_64-w64-mingw32.tar.gz"
[[XSLT]]
arch = "armv7l"
git-tree-sha1 = "244abd93cfd486bddf8d4b3cfd2c23ca7cc68916"
libc = "glibc"
os = "linux"

    [[XSLT.download]]
    sha256 = "cd5bfd65c99f9cde7b1ed0bb84e3ff9ebb31a61d47ff2386a8fa10be740ec60e"
    url = "https://github.com/JuliaBinaryWrappers/XSLT_jll.jl/releases/download/XSLT-v1.1.33+1/XSLT.v1.1.33.armv7l-linux-gnueabihf.tar.gz"
[[XSLT]]
arch = "armv7l"
git-tree-sha1 = "5616dcccab354ffdd74f767f1ab2890864359118"
libc = "musl"
os = "linux"

    [[XSLT.download]]
    sha256 = "eaa11745e4595c3b4ea9e9e7e1f2b527121cb4d726fd17ba69adb5fea9bc429b"
    url = "https://github.com/JuliaBinaryWrappers/XSLT_jll.jl/releases/download/XSLT-v1.1.33+1/XSLT.v1.1.33.armv7l-linux-musleabihf.tar.gz"
[[XSLT]]
arch = "i686"
git-tree-sha1 = "36e4c6bafecb82848074b9c6da9667286c729a7f"
libc = "glibc"
os = "linux"

    [[XSLT.download]]
    sha256 = "bdcb61c36c9513e3e812e0df8d354a075d0a8317797aa3b7b066aa72a7e5ae5f"
    url = "https://github.com/JuliaBinaryWrappers/XSLT_jll.jl/releases/download/XSLT-v1.1.33+1/XSLT.v1.1.33.i686-linux-gnu.tar.gz"
[[XSLT]]
arch = "x86_64"
git-tree-sha1 = "d7986460a025b07b31efc33d7f53c5ca20b737b2"
libc = "glibc"
os = "linux"

    [[XSLT.download]]
    sha256 = "9909887c4c03327c3a7d05e0922d26be875ac605442198f43b5d8dba15850b23"
    url = "https://github.com/JuliaBinaryWrappers/XSLT_jll.jl/releases/download/XSLT-v1.1.33+1/XSLT.v1.1.33.x86_64-linux-gnu.tar.gz"
[[XSLT]]
arch = "powerpc64le"
git-tree-sha1 = "9f363f498cf02d3a1b937bb462853a5faa554ab8"
libc = "glibc"
os = "linux"

    [[XSLT.download]]
    sha256 = "7f1dcd152a82394dc2fad9592a54e39c98102279fce6a52dc4d223d8c461b18a"
    url = "https://github.com/JuliaBinaryWrappers/XSLT_jll.jl/releases/download/XSLT-v1.1.33+1/XSLT.v1.1.33.powerpc64le-linux-gnu.tar.gz"
[[XSLT]]
arch = "x86_64"
git-tree-sha1 = "359b34c49dd0688b79ba59c605b85dd1c015ca36"
os = "macos"

    [[XSLT.download]]
    sha256 = "5e6915a04b6f9deb0cb648260f402d0dfd6f4d93a6dfb9f8f6d6ba597aa2a60b"
    url = "https://github.com/JuliaBinaryWrappers/XSLT_jll.jl/releases/download/XSLT-v1.1.33+1/XSLT.v1.1.33.x86_64-apple-darwin14.tar.gz"
[[XSLT]]
arch = "aarch64"
git-tree-sha1 = "dee7b1b712488ebd7114275eccfa6000935a961e"
libc = "glibc"
os = "linux"

    [[XSLT.download]]
    sha256 = "e8c0e2e5a9e97e2c9e9d6a9cbbae846b9633876a86338258eba94de1b38e239f"
    url = "https://github.com/JuliaBinaryWrappers/XSLT_jll.jl/releases/download/XSLT-v1.1.33+1/XSLT.v1.1.33.aarch64-linux-gnu.tar.gz"
[[XSLT]]
arch = "x86_64"
git-tree-sha1 = "cb16e1f879cc649194deb93e2a0109e9e2e32e44"
os = "freebsd"

    [[XSLT.download]]
    sha256 = "21ffd6727976e5c34d231c4a4ed9c37ddfa9ace5d4d781fc231d693ffe0ee542"
    url = "https://github.com/JuliaBinaryWrappers/XSLT_jll.jl/releases/download/XSLT-v1.1.33+1/XSLT.v1.1.33.x86_64-unknown-freebsd11.1.tar.gz"
[[XSLT]]
arch = "x86_64"
git-tree-sha1 = "50451432709f31aeffc0d7586bea34f2b95764ca"
libc = "musl"
os = "linux"

    [[XSLT.download]]
    sha256 = "c2a62d72027199da58a90135e087a4d90583985f29d7809752ed9d976728af5c"
    url = "https://github.com/JuliaBinaryWrappers/XSLT_jll.jl/releases/download/XSLT-v1.1.33+1/XSLT.v1.1.33.x86_64-linux-musl.tar.gz"
