[[XSLT]]
arch = "aarch64"
git-tree-sha1 = "e6c2b6243df385be8b94039b3d30aade1a0db85b"
os = "macos"

    [[XSLT.download]]
    sha256 = "993dcf136fc51b534e8239c9fdb8c48484ad533fecb3d316311690bbe33a9cbd"
    url = "https://github.com/JuliaBinaryWrappers/XSLT_jll.jl/releases/download/XSLT-v1.1.41+0/XSLT.v1.1.41.aarch64-apple-darwin.tar.gz"
[[XSLT]]
arch = "aarch64"
git-tree-sha1 = "c23ed1a4fe35a58b4107c85f2ca149fac10cd088"
libc = "glibc"
os = "linux"

    [[XSLT.download]]
    sha256 = "74a4a9d7464ab249cc61efe681c14e6e93cc9a331845c3cc45c6fe5d0da005f7"
    url = "https://github.com/JuliaBinaryWrappers/XSLT_jll.jl/releases/download/XSLT-v1.1.41+0/XSLT.v1.1.41.aarch64-linux-gnu.tar.gz"
[[XSLT]]
arch = "aarch64"
git-tree-sha1 = "9e3e7cd02a7fa908ac38d8cc868c27abf8419174"
libc = "musl"
os = "linux"

    [[XSLT.download]]
    sha256 = "3fba1bfe8eaefb814fdd455592dbc2184d37e940d08b607baf448fa6a681e343"
    url = "https://github.com/JuliaBinaryWrappers/XSLT_jll.jl/releases/download/XSLT-v1.1.41+0/XSLT.v1.1.41.aarch64-linux-musl.tar.gz"
[[XSLT]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d4bf8c8a1cde55b5d32ac6ac008738c06074086e"
libc = "glibc"
os = "linux"

    [[XSLT.download]]
    sha256 = "d8bd69314e3a35e18c94cba9397f7bf92fd7faa1aca03f14a18219c61be820cb"
    url = "https://github.com/JuliaBinaryWrappers/XSLT_jll.jl/releases/download/XSLT-v1.1.41+0/XSLT.v1.1.41.armv6l-linux-gnueabihf.tar.gz"
[[XSLT]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "576ad7518272735df17d86f0d7dc06ebe78dc5e3"
libc = "musl"
os = "linux"

    [[XSLT.download]]
    sha256 = "0dc6e2eb96377edc9d69512ff27323709a8b94ad22f4a0cd3332716bb063d2e8"
    url = "https://github.com/JuliaBinaryWrappers/XSLT_jll.jl/releases/download/XSLT-v1.1.41+0/XSLT.v1.1.41.armv6l-linux-musleabihf.tar.gz"
[[XSLT]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "9118fc8373c924d77126746c56c36e95cbc20ca6"
libc = "glibc"
os = "linux"

    [[XSLT.download]]
    sha256 = "4bd28319b25091e8e21f6f1cc55a6cee750955e641a1a0ead3eb13debb4f640f"
    url = "https://github.com/JuliaBinaryWrappers/XSLT_jll.jl/releases/download/XSLT-v1.1.41+0/XSLT.v1.1.41.armv7l-linux-gnueabihf.tar.gz"
[[XSLT]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "4287a2694f1b03f9d0fa5181e35bafabdcafcce6"
libc = "musl"
os = "linux"

    [[XSLT.download]]
    sha256 = "4b863cbd5fef4e8c1904a0dd05bff7e0847d9bc1c54f0ffc465e83b4144e1c84"
    url = "https://github.com/JuliaBinaryWrappers/XSLT_jll.jl/releases/download/XSLT-v1.1.41+0/XSLT.v1.1.41.armv7l-linux-musleabihf.tar.gz"
[[XSLT]]
arch = "i686"
git-tree-sha1 = "8f9794c890f63096e44a50b51d67b08bae140c08"
libc = "glibc"
os = "linux"

    [[XSLT.download]]
    sha256 = "8a7b011cb72b3c7f93caa0d943ceadd072025371eee4f137892b450cd67fc1fb"
    url = "https://github.com/JuliaBinaryWrappers/XSLT_jll.jl/releases/download/XSLT-v1.1.41+0/XSLT.v1.1.41.i686-linux-gnu.tar.gz"
[[XSLT]]
arch = "i686"
git-tree-sha1 = "96a5faacd2b8a12d28afa56949e8a408a28e2647"
libc = "musl"
os = "linux"

    [[XSLT.download]]
    sha256 = "3855161fe6127264b48ec540f2c0b88a60d1e71882f7ce8b831839df1e78e82c"
    url = "https://github.com/JuliaBinaryWrappers/XSLT_jll.jl/releases/download/XSLT-v1.1.41+0/XSLT.v1.1.41.i686-linux-musl.tar.gz"
[[XSLT]]
arch = "i686"
git-tree-sha1 = "7c21f92926cb104027c8bbbb81038d40add50a85"
os = "windows"

    [[XSLT.download]]
    sha256 = "7dd1750d95938b26cc88199f8f12bfe386c828607bb5948663f72bb576c0137d"
    url = "https://github.com/JuliaBinaryWrappers/XSLT_jll.jl/releases/download/XSLT-v1.1.41+0/XSLT.v1.1.41.i686-w64-mingw32.tar.gz"
[[XSLT]]
arch = "powerpc64le"
git-tree-sha1 = "22ecbfcd184c6dc1733254eaf58cb0653c8ed294"
libc = "glibc"
os = "linux"

    [[XSLT.download]]
    sha256 = "e28b246fdb194bf04c0a93e06dea9972d3cc6a557964707d7048415fc2936a47"
    url = "https://github.com/JuliaBinaryWrappers/XSLT_jll.jl/releases/download/XSLT-v1.1.41+0/XSLT.v1.1.41.powerpc64le-linux-gnu.tar.gz"
[[XSLT]]
arch = "x86_64"
git-tree-sha1 = "e2de36f8ebaae6947e581635ae7de6cd07d532ff"
os = "macos"

    [[XSLT.download]]
    sha256 = "7e3b57e27f75178f52191eb345687f6dd9c146d303e785008982112c4e2b13d7"
    url = "https://github.com/JuliaBinaryWrappers/XSLT_jll.jl/releases/download/XSLT-v1.1.41+0/XSLT.v1.1.41.x86_64-apple-darwin.tar.gz"
[[XSLT]]
arch = "x86_64"
git-tree-sha1 = "aae093c71ea1b1dc04c457afcae880d26c532115"
libc = "glibc"
os = "linux"

    [[XSLT.download]]
    sha256 = "0a4369396e90857922698247d81277d375e8b8bdd46349b7a8ff9cd24e9e4de5"
    url = "https://github.com/JuliaBinaryWrappers/XSLT_jll.jl/releases/download/XSLT-v1.1.41+0/XSLT.v1.1.41.x86_64-linux-gnu.tar.gz"
[[XSLT]]
arch = "x86_64"
git-tree-sha1 = "3f08fe42d8f509be1c55374889f5c17f1045d7a3"
libc = "musl"
os = "linux"

    [[XSLT.download]]
    sha256 = "c48e721ca49acdc872e4a088a6abc04982f860bd05e1b57977ed410ffd9ccf20"
    url = "https://github.com/JuliaBinaryWrappers/XSLT_jll.jl/releases/download/XSLT-v1.1.41+0/XSLT.v1.1.41.x86_64-linux-musl.tar.gz"
[[XSLT]]
arch = "x86_64"
git-tree-sha1 = "9e9dbc55f0e0caa6aa766bdd2388e729e812b691"
os = "freebsd"

    [[XSLT.download]]
    sha256 = "d5796fe0fdd133ed55b85cf207678b8c315216c9615c820710195e006eab5e31"
    url = "https://github.com/JuliaBinaryWrappers/XSLT_jll.jl/releases/download/XSLT-v1.1.41+0/XSLT.v1.1.41.x86_64-unknown-freebsd.tar.gz"
[[XSLT]]
arch = "x86_64"
git-tree-sha1 = "92bf8bdbbf6723befb90fa6178134a0f2cda151d"
os = "windows"

    [[XSLT.download]]
    sha256 = "962aab559757167ad5f3ff984015849f16391d6d7307dd61e7bb1276e6f96e35"
    url = "https://github.com/JuliaBinaryWrappers/XSLT_jll.jl/releases/download/XSLT-v1.1.41+0/XSLT.v1.1.41.x86_64-w64-mingw32.tar.gz"
